#! /usr/bin/env python

"""This is a Python file."""

import unittest

__author__ = "Nick Pascucci (npascut1@gmail.com)"


class MyTest(unittest.TestCase):
   def setUp(self):
       pass

   def tearDown(self):
       pass


if __name__ == "__main__":
   unittest.main()